version: '3.9'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

volumes:
  db-data:
